AccountKeyFile = account.key
CSRFile = domain.csr
ACMEDirectory = https://acme-staging-v02.api.letsencrypt.org/directory

# To be reached by ACME provider (e.g. to warn about
# certificate expiration)
#Contacts = mailto:mail@example.com;mailto:mail2@example.org

# Optional to hint ACME server about your preferred language
#Language = en

# By default, acme-dns-tiny request a certificate chain with format
# "application/pem-certificate-chain"
# With this format, you can assume the first certificate block is the one for
# your domains, as the ACME RFC force the format to have this certificate first.
#
#CertificateFormat = application/pem-certificate-chain

# Optional: Number of seconds to wait before ACME requests time out
# Default: 10
#Timeout = 10

[TSIGKeyring]
# Required TSIG key name / TSIG key value in base64 /  TSIG algorithm
KeyName = host-example
KeyValue = XXXXXXXXXXX==
Algorithm = hmac-sha256

[DNS]
# Optional name server IP address list to use instead of system dns resolver
# If multiple IP addresses has to be written, separate them by a comma
# NameServer

# Optional time to live (TTL) value used to add DNS entries
# Default: 10 seconds
TTL = 10

# Optional: Number of seconds to wait before DNS queries time out
# Default: 10
#Timeout = 10
